health_test/account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('<slug:test_slug>/', views.get_results, name='get_results'),
    path(
        '<slug:test_slug>/delete/<int:result_id>/',
        views.delete_result,
        name='delete_result'
    ),
    path(
        '<slug:test_slug>/change/<int:result_id>/',
        views.edit_result,
        name='edit_result'
    ),
]

health_test/api/urls.py
from django.urls import include, path
from rest_framework import routers
from api import views


app_name = 'api'

router = routers.DefaultRouter()
router.register(r'tests', views.TestViewSet)
router.register(r'results', views.ResultsViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include(
        'rest_framework.urls',
        namespace='rest_framework'
        )
    ),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
]

health_test/health_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from . import settings
from core.sitemaps import TestSitemap


sitemaps = {
    'test': TestSitemap
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    # Все адреса с префиксом /auth
    # будут прернаправлены в модуль django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('tests.urls', namespace='tests')),
    path('account/', include('account.urls', namespace='account')),
    path(
        'sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('api/', include('api.urls', namespace='api')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
        #document_root=settings.STATICFILES_DIRS
    )

health_test/users/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import SignUp

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        # Прямо в описании обработчика укажем шаблон,
        # который должен применяться для отображения возвращаемой страницы.
        # Да, во view-классах так можно! Как их не полюбить.
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    # Полный адрес страницы регистрации - auth/signup/,
    # но префикс auth/ обрабатывется в головном urls.py
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'login/',
        views.LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

health_test/api/models.py
from django.db import models

# Create your models here.

health_test/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

health_test/account/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from tests.models import UserResults, Test
import json


@login_required
def profile(request):
    user_results = UserResults.objects.filter(user=request.user)
    data = [float(result.result) for result in user_results]
    unique = user_results.values('test_id').distinct()
    tests = [Test.objects.get(id=test['test_id']) for test in unique]
    context = {
        'mail': 'ignatdan',
        'data': data,
        'tests': tests
    }
    return render(request, 'account/profile.html', context=context)


@login_required
def get_results(request, test_slug):
    test = get_object_or_404(Test, slug=test_slug)
    user_results = UserResults.objects.filter(user=request.user).filter(
        test=test.id
    )
    results = [float(result.result) for result in user_results]
    if len(results) == 0:
        return redirect('account:profile')
    minimum = int(min(results))
    maximum = int(max(results)) + 1
    # Это нужно для корректно отправки данных для javascript
    results = json.dumps(results)
    day = [result.date.strftime("%Y-%m-%d") for result in user_results]
    context = {
        'mail': 'ignatdan',
        'results': results,
        'min': minimum,
        'max': maximum,
        'test': test,
        'day': day,
        'user_results': user_results
    }
    return render(request, 'account/test_results.html', context=context)


@login_required
def delete_result(request, test_slug, result_id):
    user_result = get_object_or_404(UserResults, id=result_id)
    user_result.delete()
    return redirect('account:get_results', test_slug=test_slug)


@login_required
def edit_result(request, test_slug, result_id):
    user_result = get_object_or_404(UserResults, id=result_id)
    new_result = request.POST.get('result')
    if not new_result:
        return redirect('account:get_results', test_slug=test_slug)
    user_result.result = request.POST['result']
    user_result.save()
    return redirect('account:get_results', test_slug=test_slug)

health_test/api/views.py
from rest_framework import viewsets
from rest_framework import permissions

from tests.models import Test, UserResults
from .serializers import TestSerializer, ResultsSerializer


class TestViewSet(viewsets.ModelViewSet):
    queryset = Test.objects.all()
    serializer_class = TestSerializer
    permission_classes = [permissions.IsAuthenticated]


class ResultsViewSet(viewsets.ModelViewSet):
    queryset = UserResults.objects.all()
    serializer_class = ResultsSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return UserResults.objects.filter(user=self.request.user)

health_test/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    # Переменная exception содержит отладочную информацию,
    # выводить её в шаблон пользователской страницы 404 мы не станем
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

health_test/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('tests:index')
    template_name = 'users/signup.html'

health_test/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Тетсирование своего организма. Узнать свое физическое состояние.">
    <meta name="yandex-verification" content="68fceae3105520ab" />
    
    <title>
      {% block title %}
      {% endblock %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/checkout/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="shortcut icon" type="/image/x-icon" sizes="16x16" href="{% static 'img/main.png' %}">
    <link rel="icon" type="/image/x-icon" sizes="16x16" href="{% static 'img/main.png' %}">
    <meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/test.css' %}" rel="stylesheet">
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
  </head>
  <body>

<header>
    {% include 'includes/header.html' %}
</header>

<main>
  {% block content %}
  {% endblock %}
</main>
 
  <footer class="container">
    {% include 'includes/footer.html' %}
  </footer>

  </body>
</html>

health_test/templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Custom CSRF check error{% endblock %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

health_test/templates/includes/footer.html
{% load static %}

<!-- <p class="float-end"><a href="#">Вернуться наверх</a></p> -->

health_test/templates/includes/header.html
{% load static %}

  <nav class="navbar navbar-expand-lg navbar-light pb-3 mb-4 fixed-top border-bottom bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'tests:index' %}">Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse " id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          <!--<li class="nav-item">
            <a class="nav-link" aria-current="page" href="#">Личный кабинет</a>
          </li> -->
          <li class="nav-item">
            <a class="nav-link disabled" href="">Тесты (на этапе тестирования)</a>
          </li>
          <li>
            <a class="nav-link disabled" href="">Новости (на этапе тестирования)</a>
          </li>
        </ul>
        <ul class="navbar-nav me-2 justify-content-end">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "account:profile" %}">Личный кабинет {{user.first_name}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url "users:logout" %}">Выйти</a>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "users:login" %}">Вход</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{% url "users:signup" %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

health_test/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

health_test/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}

{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

health_test/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="form-group row my-3">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}